package ${javaPackage};

import org.springframework.stereotype.Repository;
import ${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Dao.classPath")!""};
import ${commonValueStack.getValue("BaseDao.classPath")!""};
/**
* ${tableMeta.table.comment!''}
* code generated by tool
*/
@Repository("${tableCamelNameMin}Dao")
public class ${javaClassName} extends BaseDao<${tableCamelNameMax}DO, ${tableCamelNameMax}Query> implements ${tableCamelNameMax}Dao{

    private static final String NAMESPACE = "${tableCamelNameMax}.";

	@Override
	protected String getNamespace() {
		return NAMESPACE;
	}

}

