package ${javaPackage};

import ${commonValueStack.getValue(tableCamelNameMax + "Manager.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "DTO.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "RemoteService.classPath")!""};
import ${commonValueStack.getValue("PagedResultsResponse.classPath")!""};
import ${commonValueStack.getValue("Response.classPath")!""};
import ${commonValueStack.getValue("PagedResult.classPath")!""};
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.ArrayList;

/**
* ${tableMeta.table.comment!''}
* code generated by tool
*/
@Service("${tableCamelNameMin}Service")
public class ${javaClassName} implements ${tableCamelNameMax}Service {

    private Logger logger = LoggerFactory.getLogger(this.getClass());

    @Autowired
    private ${tableCamelNameMax}Manager ${tableCamelNameMin}Manager;


    @Override
    public Response<Long> insert(${tableCamelNameMax}DTO ${tableCamelNameMin}DTO) {
        if (null == ${tableCamelNameMin}DTO) {
            return Response.writeError("插入数据为空");
        }
        try {
            ${tableCamelNameMax}DO ${tableCamelNameMin}DO = new ${tableCamelNameMax}DO();
            BeanUtils.copyProperties(${tableCamelNameMin}DTO, ${tableCamelNameMin}DO);
            return Response.writeSuccess(${tableCamelNameMin}Manager.insert(${tableCamelNameMin}DO));
        } catch (Exception e) {
            logger.error("${tableMeta.table.comment!''}数据保存异常", e);
            return Response.writeError("${tableMeta.table.comment!''}数据保存异常");
        }
    }

    @Override
    public Response<Integer> updateById(${tableCamelNameMax}DTO ${tableCamelNameMin}DTO) {
        if (null == ${tableCamelNameMin}DTO) {
            return Response.writeError("更新数据为空");
        }
        try {
            ${tableCamelNameMax}DO ${tableCamelNameMin}DO = new ${tableCamelNameMax}DO();
            BeanUtils.copyProperties(${tableCamelNameMin}DTO, ${tableCamelNameMin}DO);
            return Response.writeSuccess(${tableCamelNameMin}Manager.updateById(${tableCamelNameMin}DO));
        } catch (Exception e) {
            logger.error("${tableMeta.table.comment!''}数据更新异常", e);
            return Response.writeError("${tableMeta.table.comment!''}数据更新异常");
        }
    }

    @Override
    public Response<Integer> deleteById(Long id) {
        if(null == id){
            return Response.writeError("删除id为空");
        }
        try {
            return Response.writeSuccess(${tableCamelNameMin}Manager.deleteById(id));
        } catch (Exception e) {
            logger.error("${tableMeta.table.comment!''}数据删除异常", e);
            return PagedResultsResponse.writeError("${tableMeta.table.comment!''}数据删除异常");
        }
    }

    @Override
    public PagedResultsResponse<${tableCamelNameMax}DTO> query(${tableCamelNameMax}Query ${tableCamelNameMin}Query) {
        if (null == ${tableCamelNameMin}Query) {
            return PagedResultsResponse.writeError("查询条件为空");
        }
        try {
            PagedResult<${tableCamelNameMax}DO> result = ${tableCamelNameMin}Manager.query(${tableCamelNameMin}Query);
            List<${tableCamelNameMax}DO> doList = result.getData();
            List<${tableCamelNameMax}DTO> dtoList = new ArrayList<>();
            for(${tableCamelNameMax}DO ${tableCamelNameMin}DO : doList){
                ${tableCamelNameMax}DTO ${tableCamelNameMin}DTO = new ${tableCamelNameMax}DTO();
                BeanUtils.copyProperties(${tableCamelNameMin}DO, ${tableCamelNameMin}DTO);
                dtoList.add(${tableCamelNameMin}DTO);
            }
            return PagedResultsResponse.writeSuccess(dtoList, result.toPagination());
        } catch (Exception e) {
            logger.error("${tableMeta.table.comment!''}数据查询异常", e);
            return PagedResultsResponse.writeError("${tableMeta.table.comment!''}数据查询异常");
        }
    }

    @Override
    public Response<List<${tableCamelNameMax}DTO>> queryAll(${tableCamelNameMax}Query ${tableCamelNameMin}Query){
        if (null == ${tableCamelNameMin}Query) {
            return PagedResultsResponse.writeError("查询条件为空");
        }
        try {
            List<${tableCamelNameMax}DO> doList = ${tableCamelNameMin}Manager.queryAll(${tableCamelNameMin}Query);
            List<${tableCamelNameMax}DTO> dtoList = new ArrayList<>();
            for(${tableCamelNameMax}DO ${tableCamelNameMin}DO : doList){
                ${tableCamelNameMax}DTO ${tableCamelNameMin}DTO = new ${tableCamelNameMax}DTO();
                BeanUtils.copyProperties(${tableCamelNameMin}DO, ${tableCamelNameMin}DTO);
                dtoList.add(${tableCamelNameMin}DTO);
            }
            return Response.writeSuccess(dtoList);
        } catch (Exception e) {
            logger.error("${tableMeta.table.comment!''}数据查询异常", e);
            return Response.writeError("${tableMeta.table.comment!''}数据查询异常");
        }
    }

    @Override
    public Response<${tableCamelNameMax}DTO> queryById(Long id) {
		if (id == null || id <= 0) {
			return Response.writeError("指定的查询Id无效");
		}
		try {
        	${tableCamelNameMax}DO ${tableCamelNameMin}DO = ${tableCamelNameMin}Manager.queryById(id);
			${tableCamelNameMax}DTO ${tableCamelNameMin}DTO = new ${tableCamelNameMax}DTO();
			BeanUtils.copyProperties(${tableCamelNameMin}DO, ${tableCamelNameMin}DTO);
			return Response.writeSuccess(${tableCamelNameMin}DTO);
		} catch (Exception e) {
			logger.error("${tableMeta.table.comment!''}数据查询异常", e);
			return Response.writeError("${tableMeta.table.comment!''}数据查询异常");
		}
    }

    @Override
    public Response<List<${tableCamelNameMax}DTO>> queryByIds(List<Long> ids) {
        if (ids == null || ids.size() == 0) {
            return Response.writeError("指定的查询Id无效");
        }
        try {
            List<${tableCamelNameMax}DO> doList = ${tableCamelNameMin}Manager.queryByIds(ids);
            List<${tableCamelNameMax}DTO> dtoList = new ArrayList<>();
            if(null != doList && doList.size() > 0){
                for(${tableCamelNameMax}DO ${tableCamelNameMin}DO : doList){
                    ${tableCamelNameMax}DTO ${tableCamelNameMin}DTO = new ${tableCamelNameMax}DTO();
                    BeanUtils.copyProperties(${tableCamelNameMin}DO, ${tableCamelNameMin}DTO);
                    dtoList.add(${tableCamelNameMin}DTO);
                }
            }
            return Response.writeSuccess(dtoList);
        } catch (Exception e) {
            logger.error("${tableMeta.table.comment!''}数据查询异常", e);
            return Response.writeError("${tableMeta.table.comment!''}数据查询异常");
        }
    }

    @Override
    public Response<Integer> batchUpdateById(List<${tableCamelNameMax}DTO> list) {
        if (list == null || list.size() == 0) {
            return Response.writeError("批量更新的数据为空");
        }
        try {
            List<${tableCamelNameMax}DO> doList = new ArrayList<>();
            if(null != list && list.size() > 0){
                for(${tableCamelNameMax}DTO ${tableCamelNameMin}DTO : list){
                    ${tableCamelNameMax}DO ${tableCamelNameMin}DO = new ${tableCamelNameMax}DO();
                    BeanUtils.copyProperties(${tableCamelNameMin}DTO, ${tableCamelNameMin}DO);
                    doList.add(${tableCamelNameMin}DO);
                }
            }
            return Response.writeSuccess(${tableCamelNameMin}Manager.batchUpdateById(doList));
        } catch (Exception e) {
            logger.error("${tableMeta.table.comment!''}数据更新异常", e);
            return Response.writeError("${tableMeta.table.comment!''}数据更新异常");
        }
    }
}