package ${javaPackage};

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * code generated by tool
 */
public abstract class AbstractController {

    private Logger logger = LoggerFactory.getLogger(this.getClass());


    protected Long getUserId(){
        //TODO parse userId
        return null;
    }

}