package ${javaPackage};

import com.alibaba.druid.stat.DruidStatManagerFacade;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
* code generated by tool
*/
@RestController
@RequestMapping("/druid")
public class ${javaClassName}{

    @RequestMapping("/monitor")
    public Object monitor() {
        return DruidStatManagerFacade.getInstance().getDataSourceStatDataList();
    }


}

