package ${javaPackage};

import java.util.List;
import ${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""};
import ${commonValueStack.getValue("PagedResult.classPath")!""};

/**
* ${tableMeta.table.comment!''}
* code generated by tool
*/
public interface ${javaClassName} {


    Long insert(${tableCamelNameMax}DO ${tableCamelNameMin}DO);

    Integer updateById(${tableCamelNameMax}DO ${tableCamelNameMin}DO);

    Integer deleteById(Long id);

    PagedResult<${tableCamelNameMax}DO> query(${tableCamelNameMax}Query ${tableCamelNameMin}Query);

    ${tableCamelNameMax}DO queryById(Long id);

    List<${tableCamelNameMax}DO> queryByIds(List<Long> ids);

    List<${tableCamelNameMax}DO> queryAll(${tableCamelNameMax}Query ${tableCamelNameMin}Query);

    Integer batchUpdateById(List<${tableCamelNameMax}DO> list);

    void batchInsert(List<${tableCamelNameMax}DO> list);

    Integer count(${tableCamelNameMax}Query ${tableCamelNameMin}Query);
}

