package ${javaPackage};

import ${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""};
import ${commonValueStack.getValue("AbstractManager.classPath")!""};
import ${commonValueStack.getValue("${tableCamelNameMax}Mapper.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Manager.classPath")!""};
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* ${tableMeta.table.comment!''}
* code generated by tool
*/
@Component("${tableCamelNameMin}Manager")
public class ${javaClassName} extends AbstractManager<${tableCamelNameMax}DO,${tableCamelNameMax}Query> implements ${tableCamelNameMax}Manager {


    @Autowired
    protected ${javaClassName}(${tableCamelNameMax}Mapper mapper) {
        super(mapper);
    }
}

