<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "mybatis-3-mapper.dtd" >
<mapper namespace="${tableCamelNameMax}">

    <!-- code generated by tool -->

    <resultMap id="${tableCamelNameMax}Result" type="${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""}">
    <#list tableMeta.fields as field>
    <result column="${field.column.columnName}" property="${field.fieldCamelNameMin}"/>
    </#list>
    </resultMap>

    <sql id="selectColumnList">
    <trim prefix="" suffixOverrides=",">
<#list tableMeta.fields as field>
    ${field.column.columnName},
</#list>
    </trim>
    </sql>

    <sql id="queryWhereSql">
        where 1=1
    <#if deleteStr?exists>
        and <#list commonValueStack.getSpecifiedFields(tableMeta.fields,deleteStr) as field>${field.column.columnName}=0</#list>
    </#if>
<#list tableMeta.fields as field>
    <if test="${field.fieldCamelNameMin} != null">
        and ${field.column.columnName}=${r'#'}{${field.fieldCamelNameMin}}
    </if>
</#list>
<#list commonValueStack.getSpecifiedFields(tableMeta.fields,inStr) as field>
    <if test="${field.fieldCamelNameMin}List != null and ${field.fieldCamelNameMin}List.size() > 0">
        and ${field.column.columnName} in
        <foreach collection="${field.fieldCamelNameMin}List" item="item" open="(" close=")" separator=",">
            ${r'#'}{item}
        </foreach>
    </if>
</#list>
    </sql>


    <insert id="insert" parameterType="${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""}">
        insert into ${dbName}.${tableMeta.table.tableName}(
        <trim prefix="" suffixOverrides=",">
    <#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,"id",createTimeStr,updateTimeStr,deleteStr) as field>
        ${field.column.columnName},
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,createTimeStr) as field>
        ${field.column.columnName},
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,deleteStr) as field>
        ${field.column.columnName},
    </#list>
        </trim>
        ) values(
        <trim prefix="" suffixOverrides=",">
    <#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,"id",createTimeStr,updateTimeStr,deleteStr) as field>
        ${r'#'}{${field.fieldCamelNameMin}},
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,createTimeStr) as field>
        now(),
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,deleteStr) as field>
        0,
    </#list>
        </trim>
        )
        <selectKey keyProperty="id" resultType="long" order="AFTER">
            select LAST_INSERT_ID()
        </selectKey>
    </insert>

    <insert id="batchInsert" parameterType="list">
        insert into ${dbName}.${tableMeta.table.tableName}(
        <trim prefix="" suffixOverrides=",">
    <#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,"id",createTimeStr,updateTimeStr,deleteStr) as field>
        ${field.column.columnName},
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,createTimeStr) as field>
        ${field.column.columnName},
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,deleteStr) as field>
        ${field.column.columnName},
    </#list>
        </trim>
        ) values
        <foreach collection="list" item="item" open=" " separator="," close=" ">
        (
        <trim prefix="" suffixOverrides=",">
    <#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,"id",createTimeStr,updateTimeStr,deleteStr) as field>
        ${r'#'}{item.${field.fieldCamelNameMin}},
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,createTimeStr) as field>
        now(),
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,deleteStr) as field>
        0,
    </#list>
        </trim>
        )
        </foreach>
    </insert>


    <select id="queryById" resultMap="${tableCamelNameMax}Result" parameterType="java.lang.Long">
        select
        <include refid="selectColumnList" />
        from ${dbName}.${tableMeta.table.tableName}
        where id = ${r'#'}{id}
    </select>


    <select id="queryByIds" resultMap="${tableCamelNameMax}Result" parameterType="list">
        select
        <include refid="selectColumnList" />
        from ${dbName}.${tableMeta.table.tableName}
        where id in
        <foreach collection="list" item="item" index="index" open="(" close=")" separator=",">
                ${r'#'}{item}
        </foreach>
    </select>


    <select id="query" resultMap="${tableCamelNameMax}Result" parameterType="${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""}">
        select
        <include refid="selectColumnList" />
        from ${dbName}.${tableMeta.table.tableName}
        <include refid="queryWhereSql" />
        order by id desc
        limit  ${r'#'}{startIndex},${r'#'}{pageSize}
    </select>


    <select id="count" resultType="int" parameterType="${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""}">
        select
        count(id)
        from ${dbName}.${tableMeta.table.tableName}
        <include refid="queryWhereSql" />
    </select>


    <update id="updateById" parameterType="${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""}">
        update ${dbName}.${tableMeta.table.tableName}
        <trim prefix="set" suffixOverrides=",">
    <#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,"id",createTimeStr,updateTimeStr,deleteStr) as field>
        <if test="${field.fieldCamelNameMin} != null">
            ${field.column.columnName}=${r'#'}{${field.fieldCamelNameMin}},
        </if>
    </#list>
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,updateTimeStr) as field>
        ${field.column.columnName}=now(),
    </#list>
        </trim>
        where id = ${r'#'}{id}
    </update>


    <update id="batchUpdateById" parameterType="java.util.List">
        <foreach collection="list" item="item" open=" " separator=" " close="">
            update ${dbName}.${tableMeta.table.tableName}
            <trim prefix="set" suffixOverrides=",">
        <#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,"id",createTimeStr,updateTimeStr,deleteStr) as field>
            <if test="item.${field.fieldCamelNameMin} != null">
                ${field.column.columnName}=${r'#'}{item.${field.fieldCamelNameMin}},
            </if>
        </#list>
        <#list commonValueStack.getSpecifiedFields(tableMeta.fields,updateTimeStr) as field>
            ${field.column.columnName}=now(),
        </#list>
            </trim>
            where id = ${r'#'}{item.id};
        </foreach>
    </update>

    <#if deleteStr?exists>
<update id="deleteById" parameterType="java.lang.Long">
    update ${dbName}.${tableMeta.table.tableName}
    set <#list commonValueStack.getSpecifiedFields(tableMeta.fields,deleteStr) as field>${field.column.columnName}=1</#list>,
    <#list commonValueStack.getSpecifiedFields(tableMeta.fields,updateTimeStr) as field>
        ${field.column.columnName}=now()
    </#list>
    where id = ${r'#'}{id}
</update>
    <#else>
<delete id="deleteById" parameterType="java.lang.Long">
    delete from ${dbName}.${tableMeta.table.tableName} where id = ${r'#'}{id}
</delete>
    </#if>

</mapper>