package ${javaPackage};

<#list javaImports as ipt>
import ${ipt};
</#list>
import ${commonValueStack.getValue("BaseDTO.classPath")!""};
/**
 * ${tableMeta.table.comment!''}
 * code generated by tool
 */
public class ${javaClassName} extends BaseDTO{

<#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,extendStr) as field>
	/**
	 * ${field.column.comment!''}
	 */
	private ${field.fieldType} ${field.fieldCamelNameMin};
</#list>




<#list commonValueStack.getFieldsWithoutExclude(tableMeta.fields,extendStr) as field>

	public ${field.fieldType} get${field.fieldCamelNameMax}() {
		return ${field.fieldCamelNameMin};
	}

	public void set${field.fieldCamelNameMax}(${field.fieldType} ${field.fieldCamelNameMin}) {
		this.${field.fieldCamelNameMin} = ${field.fieldCamelNameMin};
	}
</#list>

}
