package ${javaPackage};

import ${commonValueStack.getValue("BaseMapper.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""};
import org.apache.ibatis.annotations.Mapper;
/**
* ${tableMeta.table.comment!''}
* code generated by tool
*/
@Mapper
public interface ${javaClassName} extends BaseMapper<${tableCamelNameMax}DO, ${tableCamelNameMax}Query>{


}

