package ${javaPackage};

import java.io.Serializable;

/**
* 基类
* code generated by tool
*/
public class BaseDTO implements Serializable {
    private static final long serialVersionUID = -1L;



}
