package com.pos.kb.api.common;

/**
* 常量
* code generated by tool
*/
public class ResponseConstants {
    public final static String CODE_SUCCESS = "0";
    public final static String MSG_SUCCESS = "success";

    public final static String CODE_DEFAULT_FAILURE = "-1";
    public final static String MSG_DEFAULT_FAILURE = "failed";
}
