package ${javaPackage};

import java.io.Serializable;

/**
* 基类
* code generated by tool
*/
public class BaseDTO implements Serializable {
    private static final long serialVersionUID = -1L;

    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
