package ${javaPackage};


/**
* 基类
* code generated by tool
*/
public class BaseQuery extends Page {
    private static final long serialVersionUID = -1L;

    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
