package ${javaPackage};

import ${commonValueStack.getValue(tableCamelNameMax + "DO.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""};
import ${commonValueStack.getValue("Dao.classPath")!""};
/**
* ${tableMeta.table.comment!''}
* code generated by tool
*/
public interface ${javaClassName} extends Dao<${tableCamelNameMax}DO, ${tableCamelNameMax}Query>{


}

