package ${javaPackage};

import java.util.List;
import ${commonValueStack.getValue("PagedResultsResponse.classPath")!""};
import ${commonValueStack.getValue("Response.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "DTO.classPath")!""};
import ${commonValueStack.getValue(tableCamelNameMax + "Query.classPath")!""};

/**
* ${tableMeta.table.comment!''}
* code generated by tool
*/
public interface ${javaClassName} {


    Response<Long> insert(${tableCamelNameMax}DTO ${tableCamelNameMin}DTO);

    Response<Integer> updateById(${tableCamelNameMax}DTO ${tableCamelNameMin}DTO);

    Response<Integer> deleteById(Long id);

    PagedResultsResponse<${tableCamelNameMax}DTO> query(${tableCamelNameMax}Query ${tableCamelNameMin}Query);

    Response<List<${tableCamelNameMax}DTO>> queryAll(${tableCamelNameMax}Query ${tableCamelNameMin}Query);

    Response<${tableCamelNameMax}DTO> queryById(Long id);

    Response<List<${tableCamelNameMax}DTO>> queryByIds(List<Long> ids);

    Response<Integer> batchUpdateById(List<${tableCamelNameMax}DTO> list);


}